# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34b0b1071d2e5ad7298fcd2b62c752575dc3ad4d533f0b84179550199c0b1fc2a1a3a74507e2b595bce18970c48506e643ecdcf218eba1090e887f6e89f5daca

test:
  secret_key_base: 3a16675d1395546ff4df5e2d8c1e8cc2e655a7215520fb4576796c7055ef1b67e40ba2c7bbbcc17920d16f7e6654f392e9a38bd1f12008a0f196ca51257c6e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
